### ISSUE TITLE
大佬你提取soft units的链接链错了

### ISSUE THREAD

**Issue by splinter21** [Francis-Komizu/Sovits#2]
要链hubert那个
你链成了声学模型那个

**Comment by Francis-Komizu** [comment]
> 

你好，可以具体说一下哪个位置吗？我检查了一下train.ipynb和inference.ipynb，好像都是链的hubert

**Comment by splinter21** [comment]
Extract speech units
Utilize the content encoder to extract speech units in the audio.

For more information, refer to [this repo](https://github.com/bshall/acoustic-model).

这个位置

**Comment by Francis-Komizu** [comment]
> Extract speech units Utilize the content encoder to extract speech units in the audio.
> 
> For more information, refer to [this repo](https://github.com/bshall/acoustic-model).
> 
> 这个位置

谢谢！已修改
