### ISSUE TITLE
大佬，原作留了个坑你没改

### ISSUE THREAD

**Issue by splinter21** [Francis-Komizu/Sovits#3]
https://github.com/Francis-Komizu/Sovits/blob/main/data_utils.py#L156
采样率不匹配，3个占位符，填了2个数（然后被我幸运地命中了23333）

**Comment by Francis-Komizu** [comment]
> https://github.com/Francis-Komizu/Sovits/blob/main/data_utils.py#L156
> 采样率不匹配，3个占位符，填了2个数（然后被我幸运地命中了23333）
已修改，谢谢你！🥰
