### ISSUE TITLE
The google drive to download Model Natsume2.0 is broken

### ISSUE THREAD

**Issue by chiwing4** [Francis-Komizu/Sovits#5]
Google Drive shows "Sorry, the file you have requested does not exist." for Natsume2.0
https://drive.google.com/file/d/1-0s7NBk49MMJzF-aBaqfuclVgF4yJzXa/view?usp=sharing

**Comment by Francis-Komizu** [comment]
> Google Drive shows "Sorry, the file you have requested does not exist." for Natsume2.0 https://drive.google.com/file/d/1-0s7NBk49MMJzF-aBaqfuclVgF4yJzXa/view?usp=sharing

Hi, chiwing! Here's the new link: https://drive.google.com/file/d/18iJlmtmu02q5Dlc4aPKjrWMOgHlGWslA/view?usp=sharing

**Comment by chiwing4** [comment]
Got it!! Thanks for your quick reply!
